class PostsController < ApplicationController
  def index
    @posts = Post.all
  end


  def show
    @post = Post.find(params[:id])
    #find the post that corresponds to the id in the params that was passed to show &
    #assign it to @post. Unlike in the index method, in the show method,
    #populate an instance variable with a single post, rather than a collection of posts.
  end


  def new
    @post = Post.new
    #create an instance variable, @post, then assign it an empty post returned by Post.new
  end


  def create
    #When the user clicks Save, the create method is called. create either updates the database
    #with the save method, or returns an error. Unlike new, create does not have a corresponding view.
    #create works behind the scenes to collect the data submitted by the user and update the database. create is a POST action.
     @post = Post.new
     @post.title = params[:post][:title]
     @post.body = params[:post][:body]
      #call Post.new to create a new instance of Post.
     if @post.save
       flash[:notice] = "Post was saved."
       redirect_to @post
       #if we successfully save Post to the database, we display a success message
       #using flash[:notice]and redirect the user to the route generated by @post.
       #Redirecting to @post will direct the user to the posts show view.
     else
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :new
       #if we do not successfully save Post to the database,
       #we display an error message and render the new view again.
     end
   end


  def edit
  end
end
